var data = {
    header_name: 'Md. Nokibul Islam',
    about_my_self: 'Hi, I am working as a Junior Software Engineer at TMSS ICT Limited. Previously I completed my Diploma in Computer Science and Technology from the TMSS Institute of Science and ICT Of Bangladesh,Bogura. I expected to work with an organization where I shall be able to expose myself to every opportunity through a quality and growth-oriented job. The working environment should allow me to understand my own values and provide me with a dynamic & challenging career..<br>\n',
    contact_details : 'I am always open to discussing new projects, creative ideas or opportunities to be part of your visions.',
    banner_button_text: 'More about me',
    about_banner_resume_title: 'Resume',
    about_personal_info_title: 'Personal infos',
    first_name: 'Md. Nokibul Islam',

    email: 'nokibulislam720@gmail.com',
    phone: '01855214865',
    nationality: 'Bangladeshi',
    freelance: 'Available',
    address: 'Dhaka, Bangladesh',
    skype: 'MD Nokibul Islam Ridoy',
    language: 'Bengali, English',
    facebook: 'https://www.facebook.com/InocentAtik/',
    twitter: 'https://twitter.com/InocentAtik',
    linkedin: 'https://www.linkedin.com/in/atik15/',
    experience_counter: [
        {count: 5, first_text: 'years of', last_text: 'experience',},
        {count: 20, first_text: 'completed', last_text: 'projects',},
        {count: 5, first_text: 'Happy', last_text: 'customers',},
        {count: 10, first_text: 'technology', last_text: 'uses',},
    ],
    
    skills: [
        {name: 'PHP', percent: 80,},
        {name: 'Laravel', percent: 90},
        {name: 'Python', percent: 50},
        {name: 'Django', percent: 75},
        {name: 'Javascript', percent: 80},
        {name: 'Vue.Js', percent: 90},
        {name: 'Firebase', percent: 50},
        {name: 'Css', percent: 90},
        {name: 'Bootstrap', percent: 80},
        {name: 'Html', percent: 90},
        {name: 'Version Control (git)', percent: 85},
        {name: 'Docker', percent: 50},
    ],
    experiences: [
        {
            start_date: 'septembor-2021',
            end_date: 'Present',
            designation: 'Software engineer',
            company: 'TMSS-ICT',
            technology: 'PHP, Laravel, Javascript, Vue.js, Git',
            projects: 'Microfinance, Education, News, Water supply, Website'
        },
    ],
    educations: [
        {
            name: 'Diploma in Computer Science and Technology  (CST)',
            year: '2022',
            section: 'CSE',
            institute: 'TMSS Institute of Science and ICT Bogura',
            result: '3.66',
        },
        {
            name: 'Secondary School Certificate (SSC)',
            year: '2016',
            section: 'Science',
            institute: 'Shahebgonj High School',
            result: '3.72'
        },
    ],
    trainings: [
        {
            name: 'Web Development',
            year: '2016',
            institute: 'Hypertag Solution',
            duration: '4 month',
            program: 'PHP, Laravel',
        },
        {
            name: 'Web Design',
            year: '2020',
            institute: 'TMSS Institute of Science and ICT Bogura',
            duration: '4 month',
            program: 'HTML, CSS, Bootstrap, Javascript',
        },
    ],
    projects: [
        {
            project_name: 'E-Commarce (Web & Api)',
            client: 'Red Origin',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js,Firebase, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'ecommarce/',
            images: ['thumbnail.png'],
            details: '',
            url: '#',
        },


        {
            project_name: 'Microfinance Solution',
            client: 'TMSS-ICT',
            role: 'Team Member',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'mikrof/',
            images: ['thumbnail.png'],
            details: '',
            url: 'https://mikrof.com/',
        },
        {
            project_name: 'Water Supply Management',
            client: 'TMSS-ICT',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'shitol/',
            images: ['thumbnail.png'],
            details: '',
            url: '#',
        },

        {
            project_name: 'Education management information system',
            client: 'Tmss',
            role: 'Developer',
            technology: 'PHP, Laravel, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'bashuks/',
            images: ['thumbnail.png'],
            details: '',
            url: 'https://tpsc.edu.bd/frontend',
        },
        {
            project_name: 'PressPhoto (Api)',
            client: 'PressPhoto',
            role: 'Developer',
            technology: 'PHP, Laravel, Firebase',
            thumbnail: 'thumbnail.png',
            folder: 'pressphoto/',
            images: ['thumbnail.png'],
            details: '',
            url: '#',
        },
        {
            project_name: 'Etraining',
            client: 'Etraining',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.Js',
            thumbnail: 'thumbnail.png',
            folder: 'etraining/',
            images: ['thumbnail.png'],
            details: '',
            url: '#',
        },
    ],
    imageBasePath: 'img/projects/',
};
